/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.crashlytics;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.crashlytics.android.Crashlytics;
import io.fabric.sdk.android.Fabric;

@Kroll.module(name="TitaniumCrashlytics", id="ti.crashlytics")
public class TitaniumCrashlyticsModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TitaniumCrashlyticsModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public TitaniumCrashlyticsModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Fabric.with(TiApplication.getAppCurrentActivity(), new Crashlytics());
	}

	// Methods

	@Kroll.method
	public void crash()
	{
		Crashlytics.getInstance().crash();
	}

	@Kroll.method
	public void throwException()
	{
		throw new RuntimeException("This is a crash");
	}
}

